FORMAT: 1A
HOST: http://www.openbeelden.nl

# openbeelden
This is a design for the Open Beelden API for user management to guide the development process. It does not reflect the eventual Open Beelden API.

#Group User

## User [/user]

### Get all users [GET]
+ request (application/json)

+ Response 200 (vnd.collection+json)

        {
            "collection": {
                "version": "1.0",
                "href": "http://www.openbeelden.nl/api/users/",
                "items": [
                    {
                        "href": "http://www.openbeelden.nl/users/1/",
                        "data": [
                            {
                                "user": "author",
                                "value": "John Snow",
                                "prompt": "Author"
                            },
                        ]
                    }
                }
        }

### Create a new user [POST]

+ Request (application/json)

        { 
            User : [
                Gebruikersnaam : ""
                Email : ""
                Voornaam : ""
                Achternaam: ""
                Organisatienaam : ""
                Bio : ""
                Standaardlicentie: "http://creativeommons.org/licenses/CC-BY/4.0/"
            ]
        }

+ Response 201 (application/json)

        {
            Status: "Success"
            userID: "1"
        }

+ Response 400 (application/json)

        {
            Status: "Error occured"
        }

## Get individual User  [/user/{id}]

### Get user details [GET]

+ Response 200 (vnd.collection+json)

        {
            "collection": {
                "version": "1.0",
                "href": "http://www.openbeelden.nl/api/users/{id}",
                "items": [
                    {
                        "href": "http://www.openbeelden.nl/users/{id}/",
                        "data": [
                            {
                                Gebruikersnaam : ""
                                Email : ""
                                Voornaam : ""
                                Achternaam: ""
                                Organisatienaam : ""
                                Bio : ""
                                Standaardlicentie: "http://creativeommons.org/licenses/CC-BY/4.0/"
                            },
                        ]
                    }
                }
        }

### Update user details [PUT]

+ Request (application/json)

        { 
            User : [
                Gebruikersnaam : ""
                Email : ""
                Voornaam : ""
                Achternaam: ""
                Organisatienaam : ""
                Bio : ""
                Standaardlicentie: "http://creativeommons.org/licenses/CC-BY/4.0/"
            ]
        }

+ Response 201 (application/json)

        {
            Status: "Success"
            userID: "1"
        }

+ Response 400 (application/json)

        {
            Status: "Error occured"
        }

### Delete user [DELETE]

+ Response 201 (application/json)

        {
            Status: "Success"
            userID: "1"
        }

+ Response 400 (application/json)

        {
            Status: "Error occured"
        }

## User Rights [/user/{id}/rights]

### Get user Rights [GET]

+ Response 200 (vnd.collection+json)

        {
            "collection": {
                "version": "1.0",
                "href": "http://www.openbeelden.nl/api/users/{id}/rights",
                "rights": ""
            }
        }

### Update user rights [PUT]

+ Request (application/json)

        { 
            Rights : ""
        }
        
+ Response 201 (application/json)

        {
            Status: "Success"
            userID: "1"
        }

+ Response 400 (application/json)

        {
            Status: "Error occured"
        }

## User API KEY [/user/{id}/APIKey]

### Get user API Key [GET]

+ Response 200 (vnd.collection+json)

        {
            "collection": {
                "version": "1.0",
                "href": "http://www.openbeelden.nl/api/users/{id}/rights",
                "api_key": ""
            }
        }

### Update user API Key [PUT]

+ Request (application/json)

        
+ Response 201 (application/json)

        {
            Status: "Success"
            api_key: ""
        }

+ Response 400 (application/json)

        {
            Status: "Error occured"
        }