FORMAT: 1A
HOST: http://www.openbeelden.nl

# openbeelden
This is a design for the Open Beelden API to guide the development process. It does not reflect the eventual Open Beelden API.

# Group Media
Most of these can be done by the current API of the S3 store
## Media [/media]
### List all Media [GET]
+ Response 200 (application/json)

        []

### Upload Media [POST]
+ Request (application/json)

        {  }

+ Response 201 (application/json)

        {}

#Group Individual Media Items

## Media/{id} [/media/{id}]
### Get individual Media record [GET]
+ Response 200 (application/json)
    
        []

### Update individual Media Record [PUT]

### Delete individual Media Record [DELETE]

#Group User

## User [/user]

### Get all users [GET]

## Get individual User 